FROM ruby:2.6.6

# rails console内で日本語を使う為。
ENV LANG C.UTF-8

# `rails credentials:edit`の為。
ENV EDITOR vim

ENV APP_ROOT /app

WORKDIR $APP_ROOT

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | \
  apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | \
  tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
    build-essential \
    nodejs \
    vim \
    yarn

# NOTE: bundle/yarn installは起動後に行う。開発時のinstallを速くする為。
